language: bash

# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll update it later)
services:
  - 'docker'

# see https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry
before_install:
 - sudo pip install jinja2 jinja2-cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

env:
 - DOCKER_PUBLISH="true"

script:
 - bash build.sh
