language: bash
services: docker

env:
  - RELEASE_NAME=6.2.3.7-rc1 REPO_NAME=strapdata/elassandra-rc
  - RELEASE_NAME=5.5.0.24-rc1 REPO_NAME=strapdata/elassandra-rc

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  # solves gpg server problems
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - image="strapdata/elassandra:$VERSION"

script: |
    (
      set -Eeuo pipefail
      set -x
      ./build.sh
      ~/official-images/test/run.sh --config ~/official-images/test/config.sh --config test/config.sh  "$image"
    )

after_script:
- docker images